sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t abdmaraqa1997/docker-react -f Dockerfile.dev .

script:
  # - docker run abdmaraqa1997/docker-react npm run test -- --coverage
  - docker run -e CI=true abdmaraqa1997/docker-react npm run test