sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t MYIMAGE -f Dockerfile.dev .

script:
  - docker run MYIMAGE npm run test -- --coverage
  # - docker run -e CI=true USERNAME/docker-react npm run test