sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t abdmaraqa1997/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true abdmaraqa1997/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "dockerreact"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-835180412860"
  bucket_path: "dockerreact"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
